name = "backend"
compatibility_date = "2024-09-11"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGU3NjQyMjItN2M3YS00NGUzLWFiYmMtZjBmNzkxNjYzNDliIiwidGVuYW50X2lkIjoiZGIxODVhOGRjNTVlZWJiMWNiZDcxMWE2N2YzY2I0MDRhMzJkODQyZmU2NzlkYjdiYjA0NTQ1NzU2NTY5OGNlNSIsImludGVybmFsX3NlY3JldCI6ImU3ZmRlYTZmLTA1MDQtNGZkYi1hYjQwLTQyZGE4ZTAwNDkwMCJ9.tG3WEtw8c7e_NAt8bm2gnsT47qZV4ePjZfzP3fh4Bic"
JWT_SECRET_KEY = "HI THERE"
